### ISSUE TITLE
Unable to save large QR codes that contain more than 265 characters (PNG & SVG)

### ISSUE THREAD

**Issue by Happy-Brick** [TheJoeFin/Simple-QR-Code-Maker#28]
![image](https://github.com/user-attachments/assets/dadbe56c-ab7f-4397-b0a7-426da45a033c)

Unable to save large QR codes that contain more than 265 characters (PNG & SVG)
The generated QR code previews are correct and complete, however.

**Steps to reproduce:** 
1) Paste the following placeholder text (or any text longer than 265 characters) in: Lorem ipsum odor amet, consectetuer adipiscing elit. Nascetur elementum nunc eleifend metus amet elit. Dignissim platea sit fringilla curae hac curabitur. Ligula euismod aliquam purus eu scelerisque scelerisque. Dictum hendrerit eleifend tempor pellentesque duis ac curabitur neque. Potenti conubia ullamcorper habitant, metus venenatis velit primis magna. Euismod proin dolor habitant placerat sagittis. Quis aptent nullam nibh pretium velit conubia lectus. Erat commodo elementum justo quis litora. Mauris fringilla nisl sem donec vehicula condimentum. Ante dis nam ligula molestie aliquam luctus cubilia eu. Dictumst molestie donec nisl maecenas ornare habitant ex metus donec. Montes sollicitudin feugiat nascetur libero fermentum. Non faucibus venenatis fusce; bibendum id ex sem elit. Magna malesuada eu platea aliquam hac est. Posuere dui nulla turpis mi himenaeos metus. Erat consectetur inceptos maecenas nisi eleifend. Malesuada varius dictum venenatis habitant odio fermentum neque sapien. Congue amet commodo sed orci; aptent pellentesque aptent sollicitudin habitasse. Ac aliquam semper ultrices dui mollis. Potenti taciti massa mus dictum fringilla, hac venenatis. Semper duis mi ipsum lacus turpis sociosqu sociosqu neque.

2) Click either "Save all to files (default)" or "Copy to clipboard"
**Expected result:** Save dialog opens/Files are copied to the clipboard
**Actual result:** Save dialog does not open/No files are copied to the clipboard

Additionally, while trying generate a large QR code and having completed the previous two steps
3) Click the "Settings" button
![image](https://github.com/user-attachments/assets/30202579-a95d-4526-b108-0081d6dc7d8c)
4) Go back
5) [Text disappears] Paste the placeholder text back in
6) Click the "Settings" button
7) Attempt to exit this menu
8) Observe the state of Theme selection menu
**Expected result:** It is possible to exit this menu; Correct theme is selected
**Actual result:** It is not possible to exit this menu; No theme is selected

**System info**
- Application version: 1.4.4.0
- OS: Windows 11 23H2
- Resolution: 1920x1080
- Scalling: 150%
- Theme: Dark

**Comment by TheJoeFin** [comment]
Hello @Happy-Brick thank you for opening this bug! I have identified this issue and fixed it in code! I'll push a new package soon
